/*
 * MyObserver.java - interface implementing half of a custom observer pattern
 *
 * Copyright (C) 2001 by Warren Milburn
 *
 */

package net.munki.util.observer;

/** Interface describing the Observer half of the Observer pattern
 */
public interface MyObserver {
    
    /** Notifies observer of events generated by observable objects
     * @param evt An object the observer can use to act on events generated by the observable object
     */    
    public void notifyEvent(Object evt);
    
}

